# Generated by Django 4.2.11 on 2024-06-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('phone', models.TextField(verbose_name='')),
                ('adress', models.TextField(verbose_name='')),
                ('postnumber', models.IntegerField()),
                ('area', models.TextField(verbose_name='')),
                ('homedate', models.DateField()),
                ('homefrom', models.TimeField()),
                ('hometo', models.TimeField()),
                ('description', models.TextField(verbose_name='')),
            ],
        ),
    ]
