# Generated by Django 5.0.6 on 2024-06-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='fetures',
            new_name='features',
        ),
    ]
