# Generated by Django 5.0.6 on 2024-06-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_fetures_rental_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rental',
            name='lon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
