# Generated by Django 5.0.6 on 2024-06-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_lat_rental_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
