# Generated by Django 4.2.11 on 2024-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_rental_lat_alter_rental_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lokal',
            field=models.BooleanField(default=False),
        ),
    ]
