# Generated by Django 5.0.6 on 2024-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_remove_rental_lat_remove_rental_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lokal_type',
            field=models.CharField(choices=[('1', 'Butik'), ('2', 'Kontor'), ('3', 'Kontorshotell'), ('4', 'Lager/Föråd'), ('5', 'P-plats/Garage'), ('6', 'Övrigt')], default='4', max_length=2),
        ),
    ]
