# Generated by Django 5.0.6 on 2024-07-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rental_lokal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='avalible_from',
            new_name='available_from',
        ),
    ]
