# Generated by Django 5.0.6 on 2024-07-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rename_avalible_from_rental_available_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
