# Generated by Django 5.0.6 on 2024-07-08 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_rental_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
