# Generated by Django 5.0.6 on 2024-07-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_rental_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='lokal_type',
            field=models.CharField(choices=[('1', 'Butik'), ('2', 'Resturang'), ('3', 'Kontor'), ('4', 'Kontorshotell'), ('5', 'Lager/Föråd'), ('6', 'P-plats/Garage'), ('7', 'Övrigt')], default='5', max_length=2),
        ),
    ]
