# Generated by Django 5.0.6 on 2024-07-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_alter_rental_lokal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='features',
            field=models.TextField(null=True),
        ),
    ]
