# Generated by Django 5.0.6 on 2024-07-10 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('buildings', '0006_images_medium_images_thumbnail_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobilenumber',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phonenumber',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.images'),
        ),
    ]
