# Generated by Django 4.2.11 on 2024-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='area',
            field=models.CharField(choices=[('1', 'Norrköping'), ('2', 'Söderköping'), ('3', 'Åby')], default='1', max_length=2),
        ),
    ]
