# Generated by Django 5.0.6 on 2024-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_building_lat_building_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to='images/medium/'),
        ),
        migrations.AddField(
            model_name='images',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/original/'),
        ),
    ]
